apiVersion: v1
kind: Namespace
metadata:
  name: ai-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ollama-open-webui-allow-scc-anyuid-default-sa
  namespace: "ai-demo"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: "ai-demo"
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
